### ISSUE TITLE
Feature class notation.

### ISSUE THREAD

**Issue by ben-marshall** [scarv/xcrypto-spec#15]
Section 2.5. Features.
- The "Base" feature class is always present in any XCrypto implementation.
- Does it make sense to include it in the `XCrypto[BASE/RND/....]` description strings? It's implicit in there being `XCrypto`.
- Removing `BASE` also lets us use the first letter of each class to be more concise:
  - `XCrypto[BASE/RND/MEM/BIT/PACK/AES/SHA3]` becomes
  - `XCrypto[RMBPAS]`
  -  Assuming we make the multi-precision letter `L` for *long*-arithmetic.

**Comment by danpage** [comment]
:thumbsup: agreed ... although I wonder how long the single-character approach will be viable *if* we need to add classes; I foresee some contrived cases, e.g., for additional special-purpose cases within class 3.

**Comment by ben-marshall** [comment]
Closing since this now seems like a non-issue. Presumably I raised it when I had fewer things to spend my time on...
