### ISSUE TITLE
PRV Interactions: mstatus.XS, mstatus.SD

### ISSUE THREAD

**Issue by ben-marshall** [scarv/xcrypto-spec#16]
The RISC-V privilidged ISA describes the `mstatus` register, section 3.1.6.
- Section 3.1.6.5 Extension Context Status in `mstatus` Register describes how implementations can signal that additional state must be saved during a context switch.
- XCrypto must have defined interractions with this, as it introduces user-level state. Our current mechanisms are too simplistic and do not fit with the *standard* RISC-V approach.

**Fields of `mstatus` to consider:**
- `XS` - Tracks the extension state, indicating if it is dirty and must be saved during a context switch.
  - The `XS` field in the `mstatus` register is a "*summary of all extensions' status*".
  - "*Every additional extension with state provides a CSR field that encodes the equivalent of the `XS` states*". XCrypto provides CSRs, but not a field to indicate `XS`. This must be added.
  - Table 3.3 of the privilidged specification shows the encoding of the 2 bit `XS` field. Their exact meaning is a little obtuse. 
 - An extension may be "*turned off*" in which case "*any instruction that attempts to read or write the corresponding state will cause an exception*".
- `SD`- The *state dirty* (?) bit indicates if any user extensions have dirty state which must be saved on a context switch. it is a function of the `FS` and `XS` fields, and need not be dealt with specially by XCrypto.

**From an XCrypto point of view:**
- Our CSRs should be ammended to include an XS field, and we should explicitly define it's behaviour. I think mirroring how the RISC-V Spec treats the `FS` field is the way to go, since we are explicitly aping a floating point co-processor with our approach.
- The spec raises the point that extensions with state should include instructions which put that state back to some "initial" condition. We've talked about it before and I think we should add this in, and extend it to include things like micro-architectural state as well as a barrier against some classes of attack[1]. Such an instuction would likely be worth while if only to make context switches 16-instructions faster/smaller.

**Concrete Actions:**
- [x] Add an `XS` field to the `XCSR` register. Ideally in bits `16:15` to mirror their position in `mstatus`.
- Add an `xc.init` instruction for putting XCrypto in a known state, architecturally and micro-architecturally. (#17)

---

1. No Security Without Time Protection: We Need a New Hardware-Software Contract
    - http://delivery.acm.org/10.1145/3270000/3265724/a1-ge.pdf

**Comment by danpage** [comment]
:thumbsup: nice work on pushing this forward; for sure it takes a step towards being more compliant! Note that the spec. notes the need to avoid attack vectors similar to LazyFP [1], which is certainly aligned with this issue.  

[1] https://arxiv.org/abs/1806.07480

**Comment by ben-marshall** [comment]
More Notes:
- The `XCSR` register needs to be shadowed and visible in user mode and supervisor mode.
  - All software needs to interrogate available instructions / hardware features.
  - For context switches, all privilidge levels need to see the `XS` bits, which would currently only be exposed at the `M` level.
- The `XCCR` register needs shadowing in the same way.
- Change the names of the current CSRs to follow the standard RISC-V conventions:
  - `XCCR` -> `mxccr`
  - `XCSR` -> `mxcsr`, `sxcsr`, `uxcsr`

I know we've flip flopped on this before, but I think we would be better moving back to a single additional CSR for XCrypto.
- Needing to make registers visible at all privilidge levels means adding 6 registers instead of 2. This would be very greedy.
- There's plenty of space in terms of bits for everything to go in one regiser.
- Only two bits of the register would be writable.

Suggested revised CSR listing for XCrypto:

Register  | Address  | Access | Privilidge
------|----------|--------|---------
`mxcsr` |  0x7C0 | RW  | M
`sxcsr` |  0xDC0 | RW  | S
`uxcsr` |  0xCC0 | R   | U

- The `m` register has all bits visible and `S`/`U` fields writable.
- The `s` register has all bits visible iff the `S` bit is set. Else it reads as all zeros.
- The `u` register has all bits visible iff the `S` and `U` bits are set. Else it reads as all zeros.
- If `S`  is clear, this implies `U` is also clear.

**Comment by ben-marshall** [comment]
Work is being done on the `dev/csr-fields` branch.
- See PR #19 
- https://github.com/scarv/xcrypto-spec/tree/dev/csr-fields

**Comment by ben-marshall** [comment]
Finished with merge of PR #19
