### ISSUE TITLE
RV64 interoperability.

### ISSUE THREAD

**Issue by ben-marshall** [scarv/xcrypto-spec#18]
Given the RISC-V community is very much of the opinion that 64-bits is the default now, it makes sense to put some notes together on how  XCrypto should operate within a 64-bit architecture. Even though we explicitly say that we are considering RV32I as the base architecture.

Issues to consider:
- Should the register-file width change?
- If the register file width does not change, this is all very simple.
  - Must account for movement between XCRs and GPRs only.
- How much does having 64-bit wide registers help or hinder?
  - Better for SWAR -> more operations.
  - How much is SWAR actually used?

**Comment by danpage** [comment]
This seems like a good opportunity to at least *think* about a more aggressive step, and what it'd mean to totally decouple XLEN (which apparently has also been generalised a bit) from the XCrypto word size. In a sense this follows the "word-size scalability" feature of PLX; we *could* capture the size as a field in the CSR.  Then the question is how specific instructions change: I think you're right wrt. those that need attention (e.g., ext, ins, and sub-word transfers), but maybe it's a good thought experiment to survey more generally?

[1] e.g., https://dl.acm.org/citation.cfm?id=1050587

**Comment by ben-marshall** [comment]
**Notes:**

- Defined `XCLEN=32` as the XCrypto word size.
- Assuming that in future we might consider `XCLEN={32,64,128}`.

**Instructions:**

The following instructions will need their behaviour re-stating in terms of `XCLEN`.
-  `xc.gpr2xcr`
-  `xc.xcr2gpr`
-  All load/store instructions in the *base* ISE.
- `xc.rngseed` and `xc.rngsamp` must seed/sample `XCLEN` bits of randomness.
- `xc.scatter.*` and `xc.gather.*`.
- `xc.ld.*iu`
- `xc.bop` restate `for i=0 to 32` as `for i =0 to XCLEN`.
- `xc.ins`/`xc.ext` immediates are too small for anything other than `XCLEN=32`.
- `xc.lut` was designed with `XCLEN=32` in mind. Would want re-designing if `XCLEN>32` due to register concatenation.
- `xc.p*` - All packed instructions need `w=32/n` restating as `w=XCLEN/n`. Re-coding of the packwidths has been a todo for a while now. Doing so would make space for wider pack widths.
- `xc.pperm.*` - All defined with immeidate encodings expecting `XCLEN=32`.
- `xc.m*` - All multi-precision instructions would scale naturally and just need definitions re-stating in terms of `XCLEN`.
  - `xc.mequ/mltu/mgeu` need their writeback value zero padded to `XLEN` bits.
- `xc.aes*` - Explicitly uses individual bytes of expected 32-bit register.
- `xc.sha3.` - Not affected by `XCLEN`.

**Comment by ben-marshall** [comment]
**Analysis:**
- It looks like it is worth re-stating the current definitions in terms of `XCLEN`, given that we keep assuming that `XCLEN=XLEN=32`.
- How should we consider `XCLEN=64/128` as with the rest of RISC-V?

Options to consider:

1. Do not modify anything, only provide defintions which assume `XCLEN = XLEN = 32`.
    - *C-* for effort.
    - This is what we have now, and it fits with our goal of being a *Crypto extension for micro-controllers*.
2. Keep `XCLEN=32`, but make no assumption about the value of `XLEN`.
   - *B+* for effort.
    - It is plausible that someone would want to attatch XCrypto to an RV64 base ISA.
    - To hear SiFive talk, there is a demand for 64-bit micro-controllers. Though this definition hinges all on *"does it have an MMU?"*, not the size of the core.
    - The base ISA being 64-bits does not make any of the equivalent riscv instruction sequences faster for the kinds of operations we accelerate. Hence there would still be some worth to add XCrypto to an RV64I based system.
    - An exception would be the multi-precision integer arithmetic instructions, which do benefit from wider registers, but not enough to make them faster than a non-unrolled XCrypto equivilent? In an unrolled implementation, RV64I is faster than XCrypto. Rolled up, the indexed load/store instructions give XCrypto the edge.
    - Instruction changes required would be minimal. Only movement between `GPR` and `XCR` registers would need additional work.
3. Assert that `XCLEN = XLEN = {32,64,128}`.
    - *A* for effort
    - Many of the XCrypto instructions would require alteration, or wide-register equivilent versions in order to handle RV64I or RV128I.
    - At this point, we are gaining generality at the expense of efficiency for our original intended use case.
4. Allow any variation of `XCLEN, XLEN = {32,64,128}` and `XCLEN` need not equal `XLEN`.
    - *A+* for effort.
    - Comes with all the problems of point *3*, plus complicating movement between `XCR` and `GPR` registers.
    - `XCLEN > XLEN` feels like it would be an insensible implementation choice.

**Overall:**
- I think that we should re-do instruction definitions in terms of `XCLEN` and,
- assert that `XCLEN` is always `32`, but re-define the `xc.gpr2xcr` and `xc.xcr2gpr` instructions to properly handle different base ISA widths.
  - This is the sweet spot in terms of problem spaces that XCrypto is designed to fill.

**Comment by ben-marshall** [comment]
As per commit f01ce46:
- The gpr/xcr move instructions have been re-defined in terms of `XCLEN`, since these are the only ones with otherwise underspecified behaviour.
- Re-stating all other instructions in terms of `XCLEN` actually makes them really unclear and messy to read.
- Seems like a lot to do if we know that `XCLEN` is going to be fixed at `32`.
