### ISSUE TITLE
Packed shift by register behavior

### ISSUE THREAD

**Issue by ben-marshall** [scarv/xcrypto-spec#27]
Currently, the spec for packed shift/rotate by register instructions (`xc.psll/psrl/prot`) are specified such that the distance they shift/rotate by is specified *per-subword value*. That is, I can shift two halfwords by two different amounts.
- That is *not* how spike, the reference implementation, benchmarks or the formal checkers are set up.
- They assume that each sub-word field is shifted/rotated by the same amount.

I don't know how this came about. I'd always assumed that everything would be shifted by the same amount and probably didn't read the specification clearly enough to query it earlier.

What now?

**Comment by danpage** [comment]
The spec. is wrong; the implementation is right.  This looks like a copy-and-paste typo, since there are a few others in that class as well (some of the second operands weren't right: the first operand was used twice): I've fixed the spec.
